export enum JwtExpiration {
  OneMinute = '1m',
  FifteenMinutes = '15m',
  ThirtyMinutes = '30m',
  OneHour = '1h',
  TwoHours = '2h',
  FourHours = '4h',
  SixHours = '6h',
  TwelveHours = '12h',
  OneDay = '1d',
  TwoDays = '2d',
  ThreeDays = '3d',
  OneWeek = '7d',
  TwoWeeks = '14d',
  OneMonth = '30d',
  ThreeMonths = '90d',
  SixMonths = '180d',
  OneYear = '365d',
}
